books/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, getJSON, defaultJSON, signOut, addCounter, decCounter

urlpatterns = [
    path('', index, name='index'),
    path('getDefaultJSON/', defaultJSON, name='defaultJSON'),
    path('fetchData/<str:title>', getJSON, name='getJSON'),
    path('signOut/', signOut, name='signOut'),
    path('addCounter/', addCounter, name='addCounter'),
    path('decCounter/', decCounter, name='decCounter'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('api-auth/', include(('rest_framework.urls'), namespace='rest_framework')),
    path('', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('status/', include(('status.urls', 'status'), namespace='status')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('registration/', include(('subscriber_registration.urls', 'subscriber_registration'), namespace='subscriber_registration')),
    path('sign-in/', include(('sign_in.urls', 'sign_in'), namespace='sign_in')),
]

books/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
import requests
from django.contrib.auth import logout

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

response = {}
response['counter'] = 0

def getJSON(request, title):
    data = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + title)
    return HttpResponse(data, content_type='application/json')

def defaultJSON(request):
    data = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
    return HttpResponse(data, content_type='application/json')

def index(request):
    if request.user.is_authenticated:
        if 'counter' not in request.session:
            request.session['counter'] = 0
        response['counter'] = request.session['counter']
    else:
        request.session['counter'] = 0
    return render(request, "books.html", response)

@csrf_exempt
def addCounter(request):
    if request.user.is_authenticated:
        request.session['counter'] = request.session['counter'] + 1
    return HttpResponse(request.session['counter'], content_type='application/json')

@csrf_exempt
def decCounter(request):
    if request.user.is_authenticated:
        request.session['counter'] = request.session['counter'] - 1
    return HttpResponse(request.session['counter'], content_type='application/json')

def signOut(request):
    request.session.flush()
    logout(request)
    return HttpResponseRedirect("/")

books/templates/books.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="container" style="min-height: 84vh;">
        <div class="jumbotron" style="background: -webkit-linear-gradient(top, #e5658b, #cc64b2);">
            <div class="container" style="text-align: center">
                <div class="data">
                    <img id="google-pic" class="img-circle" width="100px" height="100px" style="margin-bottom: 20px">
                    {% if user.is_authenticated %}
                        <p>{{ user.email }}</p>
                        <h1 class="display-3">Hello, {{ user.username }}!</h1>
	                {% else %}
                        <p id="email"></p>
                        <h1 class="display-3" id="name"></h1>
	                {% endif %}
                </div>
                <div class="container-form-btn">
                    {% if user.is_authenticated %}
                    <a href="{% url 'books:signOut' %}"><button class="btn btn-default" id="sign-up-btn" style="margin-top: 50px"><b>Sign Out</b></button></a>
	                {% else %}
                    <button onclick="signOut()" class="btn btn-default" id="sign-up-btn" style="margin-top: 50px"><b>Sign Out</b></button>
	                {% endif %}
                </div>
            </div>
        </div>

        <div class="container" style="margin-top: 85px">
	        {% if user.is_authenticated %}
                <p class="display-4">{{ user.username }}, please select your favorite books.</p>
	        {% else %}
                <p class="display-4" id="name2"></p>
	        {% endif %}
            <div class="d-md-flex bd-highlight">
                <div class="p-2 w-100 bd-highlight">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button id="search-books-title" class="btn btn-default" type="button"><i class="fa fa-search" aria-hidden="true"></i></button>
                        </div>
                        <input name="books-title-input" type="text" class="form-control" placeholder="Search by Title" aria-label="Search Books Title" aria-describedby="inputGroup-sizing-sm">
                    </div>
                </div>
                <div class="p-2 flex-shrink-1 bd-highlight"> <button type="button" class="btn btn-outline-danger" id="best-sellers">The New York Times® Best Sellers</button></div>
            </div>
        </div>

        <div class="container" style="margin-top: 10px">
            <div class="row">
                <div class="col-6">
                    <div class="float-left">
                        <h1>BOOKS LIST</h1>
                    </div>
                </div>

                <div class="col-6">
                    <div class="float-right">
                        <div class="container" id="count-bookmark">
                            <img src="https://img.icons8.com/color/50/000000/filled-star.png">
                            <div class="text-block">
                                {% if user.is_authenticated %}
                                    <p id="counts">{{ counter }}</p>
	                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover table-curved" id="books-table">
                <thead class="thead-dark">
                    <tr>
                        <th>No.</th>
                        <th>Title</th>
                        <th>Authors</th>
                        <th>Publisher</th>
                        <th>Published Date</th>
                        <th>Categories</th>
                        <th>Image</th>
                        <th>Add Bookmark</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

{% endblock %}