books/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, getJSON, defaultJSON, signOut, addCounter, decCounter

urlpatterns = [
    path('', index, name='index'),
    path('getDefaultJSON/', defaultJSON, name='defaultJSON'),
    path('fetchData/<str:title>', getJSON, name='getJSON'),
    path('signOut/', signOut, name='signOut'),
    path('addCounter/', addCounter, name='addCounter'),
    path('decCounter/', decCounter, name='decCounter'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('api-auth/', include(('rest_framework.urls'), namespace='rest_framework')),
    path('', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('status/', include(('status.urls', 'status'), namespace='status')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('registration/', include(('subscriber_registration.urls', 'subscriber_registration'), namespace='subscriber_registration')),
    path('sign-in/', include(('sign_in.urls', 'sign_in'), namespace='sign_in')),
]

templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="IE=edge">

    <meta name="google-signin-client_id" content="602226791509-abivehbi7a4qjejha826d61h07v3udkj.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--font-awesome.min.css-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link id="theme" rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!--<script src="https://apis.google.com/js/platform.js" async defer></script>-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link id="accordion-theme" rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

    <title>Nabila Febri Viola</title>
  </head>

  <body>
    <div class="loading"></div>
    {% include 'navbar.html' %}

      {% block content %}{% endblock %}

    {% include 'footer.html' %}

  </body>
</html>

templates/footer.html
<footer>
  <p>Created with luv for my dear Kak Pewe</p>
</footer>

templates/navbar.html
<nav id="mynavbar" class="navbar navbar-expand-lg navbar-fixed-top navbar-dark">
  <a class="navbar-brand" href="{% url 'myprofile:index' %}">NABILAFV</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myprofile:index' %}">PROFILE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'status:index' %}">STATUS</a>
      </li>
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="{% url 'books:index' %}">BOOKS</a>-->
      <!--</li>-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'subscriber_registration:index' %}">SIGN UP</a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="{% url 'sign_in:index' %}">SIGN IN</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="change-theme">CHANGE THEME</a>
      </li>
    </ul>
  </div>
</nav>